import Head from 'next/head'
import styles from "@/components/Content/content.module.css";
import React from "react";
import {Panel} from "@/components/Panel/Panel";


export default function Home() {
    return (
        <>
            <Head>
                <title>Reddit</title>
                <meta name="description" content="Generated by create next app"/>
                <meta name="viewport" content="width=device-width, initial-scale=1"/>
                <link rel="icon" href='/favicon.ico'/>
            </Head>
            <Panel>
                <div>
                    <span className={styles.authText}>Для просмотра постов необходимо пройти авторизацию</span>
                </div>
            </Panel>
        </>
    )
}
